[package]
name = "project-euler-rust-template"
version = "0.1.0"
authors = ["pete-speth <peterspethmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
